### ISSUE TITLE
OutOfMemoryError: Failed to allocate a 536870924 byte allocation with 16765216 free bytes and 250MB until OOM

### ISSUE THREAD

**Issue by joismar** [joismar/Atividade-P3-RSS#1]
Estouro de memória na AsyncTask.

--------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: br.ufpe.cin.if710.rss, PID: 7826
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:325)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:760)
     Caused by: java.lang.OutOfMemoryError: Failed to allocate a 536870924 byte allocation with 16765216 free bytes and 250MB until OOM
        at java.util.Arrays.copyOf(Arrays.java:3256)
        at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:113)
        at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
        at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:140)
        at br.ufpe.cin.if710.rss.MainActivity$FeedTask.doInBackground(MainActivity.kt:128)
        at br.ufpe.cin.if710.rss.MainActivity$FeedTask.doInBackground(MainActivity.kt:96)
        at android.os.AsyncTask$2.call(AsyncTask.java:305)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:760) 
Application terminated.
`

**Comment by joismar** [comment]
O erro estava no "out.write(buffer, 0, count)" no momento do download do arquivo.

Substituido: 
```kotlin
val out = ByteArrayOutputStream()
val buffer = ByteArray(1024)
var count: Int
count = inputStream!!.read(buffer)
while (count != -1) {
    out.write(buffer, 0, count)
}
val response = out.toByteArray()
rssFeed = String(response, charset("UTF-8"))
items = ParserRSS.parse(rssFeed)
```

Por:
```kotlin
val inputAsString = inputStream.bufferedReader().use { it.readText() }
items = ParserRSS.parse(inputAsString)
```
